### ISSUE TITLE
2.7.0.0 issues

### ISSUE THREAD

**Issue by dimamatik** [fusepowered/FuseSDKUnity#31]
1. FuseSDL->Preferences->Active Adapters are not working on Android
2. Code FuseSDKEditor contains an error on UpdateAdapters function: 
need : Directory.GetFiles(Application.dataPath, "*" + AdapterFilenames[i], SearchOption.AllDirectories)
but not Directory.GetFiles(Application.dataPath + AdapterFilenames[i], "*", SearchOption.AllDirectories)

3. Too many fields on Android (since 2.6.6.1 version):
+ 2166 com.adcolony.sdk
+ 1657 com.fusepowered.ads.adapters.Supersonic
+ 1657 com.fusepowered.ads.adapters.Vungle
etc..

without -multidex option with build for Android (feature is not present on Unity) - it is not possible to build our project with this plugin

**Comment by ak-upsight** [comment]
Hi @dimamatik ,

Can you please e-mail our support team at support@fusepowered.com with these?

Thanks!
